apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: aqua-scanner
spec:
  template:
    metadata:
      labels:
        app: aqua-scanner
      name: aqua-scanner
    spec:
      serviceAccount: aqua
      containers:
      - name: aqua-scanner
        image: aquasec/scanner-cli:3.5
        env:
          - name: ADMIN_PASSWORD
            valueFrom: 
              secretKeyRef:
                name: console-admin-password
        args: ["daemon", "--user", "administrator", "--direct-cc", "--password", "$(ADMIN_PASSWORD)", "--host", "http://aqua-web:8080"]
        volumeMounts:
          - mountPath: /var/run/docker.sock
            name: docker-socket-mount
      volumes:
        - name: docker-socket-mount
          hostPath:
            path: /var/run/docker.sock
